### ISSUE TITLE
Use Yujin's distributors map on distributors page

### ISSUE THREAD

**Issue by sameerparekh** [turtlebot/turtlebot.com#10]
We should put on http://turtlebot.com/distributors.html

The map like Yujin has here

http://kobuki.yujinrobot.com/store/ 

Discussion here: https://github.com/turtlebot/turtlebot.com/issues/4

**Comment by pvandervorst** [comment]
Done

**Comment by stonier** [comment]
Closing this - reopen if someone thinks its necessary.
