### ISSUE TITLE
Restore original zip download

### ISSUE THREAD

**Issue by mikeferguson** [turtlebot/turtlebot.com#11]
This was brought up on the mailing list -- while it is great that we are updating to have the newer TurtleBot2 docs on the site, we probably shouldn't delete the original TurtleBot design docs. There are a number of users out there who still own TurtleBot v1, and that giant zip file includes all of the mechanical CAD as well as the design docs (schematics, gerbers, etc) for the gyro boards. These are still relevant to T1 users.

Hopefully who ever removed the file, still has a copy, otherwise, @mmwise @tfoote do you guys? I think I might have one on an older laptop....

**Comment by pvandervorst** [comment]
The documentation and old "build" page for turtlebot.com have not been
deleted. They are still in the content management system.

**Comment by LucidOne** [comment]
On 07/09/2013 10:34 PM, Michael Ferguson wrote:

> This was brought up on the mailing list -- while it is great that we are updating to have the newer TurtleBot2 docs on the site, we probably shouldn't delete the original TurtleBot design docs. There are a number of users out there who still own TurtleBot v1, and that giant zip file includes all of the mechanical CAD as well as the design docs (schematics, gerbers, etc) for the gyro boards. These are still relevant to T1 users.
> 
> Hopefully who ever removed the file, still has a copy, otherwise, @mmwise @tfoote do you guys? I think I might have one on an older laptop....
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/turtlebot/turtlebot.com/issues/11

I have a copy if needed. All the TurtleBot 1 mechanical files are in our
hardware wiki, I can upload the gyro board files and the zip file if
anyone wants it.

**Comment by mikeferguson** [comment]
Can we make them somehow visible? And easy to find...

**Comment by tfoote** [comment]
How about we make a TurtleBot1 page to link to all the old resources.  And
just add a link on the main page to the left of the open hardware logo?

**Comment by tfoote** [comment]
TurtleBot 1 download is up and valid from http://download.ros.org/downloads/turtlebot/TurtleBot-Hardware-2011-07-23.zip

We need to put together the TurtleBot2 zip file.

**Comment by tfoote** [comment]
Closing this for now, new packaging is in #16
