### ISSUE TITLE
Create TurtleBot2 zip file with hardware specs. 

### ISSUE THREAD

**Issue by tfoote** [turtlebot/turtlebot.com#16]
The website still says coming soon.

**Comment by bit-pirate** [comment]
_bump_

I believe, we already have all required files: http://files.yujinrobot.com/kobuki/hardware/

Please upload / link them on the TB site.

**Comment by pvandervorst** [comment]
Great, thanks!

On Mon, Apr 14, 2014 at 10:36 PM, Marcus Liebhardt <notifications@github.com

**Comment by pvandervorst** [comment]
Change made on the website.

**Comment by bit-pirate** [comment]
In order to align with the TB1 doc we still need to make the zip file and point the link there.

**Comment by pvandervorst** [comment]
All the parts seem to be there. Do you have this on a server somewhere you
can easily make a zip file?

On Mon, Apr 14, 2014 at 10:54 PM, Marcus Liebhardt <notifications@github.com

**Comment by bit-pirate** [comment]
Here it is: http://files.yujinrobot.com/kobuki/hardware/tb2_hardware_docs.tar.gz

**Comment by bit-pirate** [comment]
@pvandervorst please update the link on the website with link to the archive above.

**Comment by pvandervorst** [comment]
Sorry about the delay. It has been changed.

On Tue, Apr 15, 2014 at 10:17 PM, Marcus Liebhardt <notifications@github.com

**Comment by bit-pirate** [comment]
> Sorry about the delay. It has been changed.

Nice.
