### ISSUE TITLE
Do we want to support 'Create Your Own' instructions?

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot.com#2]
This probably gets out of date very quickly, especially the list of suppliers etc.

Link: http://turtlebot.com/build/create.html

**Comment by stonier** [comment]
Pending #4

**Comment by bit-pirate** [comment]
Again voting for dropping this page and putting a link to the ROS wiki somwhere. There people can add/link to their TB projects.

**Comment by tfoote** [comment]
It does make senses to have it on a wiki.  The ros wiki is a little odd,
but I think it's reasonable as it's a platform for ROS adoption.

**Comment by pvandervorst** [comment]
Bill was working on his own wiki specifically for the hardware parts,
perhaps that can include instruction for manufacture?

**Comment by stonier** [comment]
Up to bill, but I think most people will find it easier if it's on the ros wiki. That is less maintainance for bill as well.

**Comment by mmwise** [comment]
i don't think the ROS wiki is the right place for it. I think we should just reduce it down to a zip file with files and instructions and possibly link out to bill's wiki, but i'm in general against linking to a specific manufacturer for any one thing.

**Comment by stonier** [comment]
I'm ok with that...also ok with it perhaps being on make projects as well. Need someone to step up and volunteer for it though - Paul may not be the right person for it.

Commented in the other thread : https://github.com/turtlebot/turtlebot.com/issues/4#issuecomment-19489576

**Comment by pvandervorst** [comment]
I agree that a zip file with all the build files will be easiest and most
accessible for everyone. I don't have this material, however. Who is
willing to help put this zip file together?

**Comment by tfoote** [comment]
Dropped in TB3 redesign
