### ISSUE TITLE
good place to upload turtlebot iso?

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot.com#21]
@LucidOne and I have worked together to develop the indigo version of turtlebot iso. 
Is there any good place to upload this?

**Comment by tfoote** [comment]
Send me a link and I can post upload it to download.ros.org

**Comment by jihoonl** [comment]
Here 

http://files.yujinrobot.com/turtlebot/iso/

**Comment by tfoote** [comment]
It's available at: http://download.ros.org/downloads/turtlebot/ubuntu-14.04.2-desktop-amd64-turtlebot-RC0.iso now

**Comment by LucidOne** [comment]
sha512sum

```
5e5000096671e69d4a1759659415aa3f31576cef82b038abbd5f18b65964088fbad7c7f8a9f219bdf363d0b4e8f8ad7d5c907d520c02a8aeb2b8a2042a4afdd3  ubuntu-14.04.2-desktop-amd64-turtlebot-RC0.iso
```
