### ISSUE TITLE
Turtlebot 3D model webview?

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot.com#23]
It would be nice if we can have turtlebot 3d webviewer hosted somewhere.

Code : https://github.com/jihoonl/dockers/tree/master/turtlebot_web_view

**Comment by tfoote** [comment]
That would be great. What level of resources would we need to host this?

**Comment by jihoonl** [comment]
@rctoris Do you have any idea what computing power would need to host urdf demo?

**Comment by jihoonl** [comment]
Basically, it only runs `robot_state_publisher`, `joint_state_publisher`, `rosbridge_webserver` and `tf2_web_republisher`. So it would require very small resource.

**Comment by rctoris** [comment]
We have ours running on an EC2 micro instance and haven't had any problems. It doesn't get any smaller than that so not sure how low it could go.

**Comment by jihoonl** [comment]
http://robotwebtools.org/demos/turtlebot-urdf.html
