### ISSUE TITLE
Do we want to support 'Turtlebot Accessories' page?

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot.com#3]
I don't think this is appropriate for the official page. These can be found at the suppliers web shops readily enough if like bill, they advertise their accessories. There are certainly no 'standard' accessories distributed by all at the moment.

Link: http://turtlebot.com/build/accessories.html

**Comment by stonier** [comment]
Pending #4

**Comment by bit-pirate** [comment]
I vote for dropping this page and adding a remark somewhere pointing out that there are accessories available and that interested people should check out the distributors' shops. We could add list of links to shops offering accessories, but then again, this list needs to be kept up to date.

**Comment by tfoote** [comment]
That seems like a good approach to me.

**Comment by rgariepy** [comment]
+1

**Comment by pvandervorst** [comment]
Agree, the accessories page is outdated and needs to be removed.

**Comment by sameerparekh** [comment]
+1, remove the accessories page

**Comment by pvandervorst** [comment]
Removed.
