### ISSUE TITLE
Redesign Thoughts

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot.com#4]
### Overview

I feel it could slim down alot. General thoughts:
- It's not easily updated like the wiki - static content as much as possible! It shouldn't be a support page, rather a portal for new users and new distributors. After coming here for the first time, they rarely come back to this page.
- Remove everything about turtlebot 1 (except maybe in the faq), turtlebot.com is not a _support_ reference. The ros wiki, ros answers and mailing list provide all of the required support for turtlebot 1. Does anyone actually sell the gyro/external power board anymore and were hobbyists making it without buying this item?
- Don't worry about build from scratch instructions as most of the distributors aren't selling components. Do include a hardware list though (with links to the stack and pole drawings). Someone can easily put together a robot from that list especially as there is now no more external power/gyro.

Given all the problems leading up to this, let's _minimise_ the amount of work we need to do to maintain this portal and most importantly, make sure there is nothing broken as it is the first page an outsider to the turtlebot community will see.
### Pages

The things that I would include (via the tabs at the top):

**Home Page**

No build/run section - these are linked from the tabs anyway. Everything else is still relevant

**Getting Started**

Hardware

Brief description of what is in the turtlebot, with pointers to the more detailed information.
- Mobile Base - point to kobuki specifications page
- Netbook - list of officially supported netbooks/laptops
- 3d Sensor - list of officially supported 3d sensors
- Stacks - link to Bill's drawings and 3d zipped files

Software

Brief summary of what constitutes the turtlebot software (ros, ubuntu based) and a link to the ros wiki where all detailed information can be found (installation and usage and tutorials).

Forget about a building from scratch I think. It's not rocket science especially since there is no longer external power boards.

**Distributors Page**

As is, probably a bit more nicely arranged as this is starting to look like a long chinese page!

Have an Icon, Name and also reserve a place where distributors can send in a paragraph to describe their role as these vary quite a bit (default empty). For example, Bill is all about accessories, Clearpath focuses on service and support, Yujin is only selling the package within Korea as an introduction to RoS.

**Links Page**

This is not just support, but also includes information, news and announcement sources. Forget about pointing to trac (now github) as that is done on the ros wiki.
- Google+
- Turtlebot sig on google groups (as the mailing list)
- Ros Answers - the place to ask questions
- Ros Wiki (http://ros.org/wiki/Robots/TurtleBot)
- FAQ

I like the faq page, though it probably needs a good update (e.g. a question about T2, updated links etc).

**Comment by stonier** [comment]
If we come to agreement on the design, I'll add issues for specific things on each page (such as broken links, old emails etc).

**Comment by mmwise** [comment]
we should add a page/section for getting in contact with OSRF (tully & melonee) about becoming a distributor and the process... etc..

**Comment by mmwise** [comment]
I think we should also leave in something about building your own.. it is an open source hardware project and the overhead for this is minimal..

**Comment by stonier** [comment]
Yeah, contact information for distributors was in the faq before melonee...probably would be good to take that out of the faq and make a separate page?

**Comment by stonier** [comment]
Does building your own need anything more than the list of hardware components and stack/pole 2d drawings?

We could I suppose - but I'm not sure I'd link to distributors pages with regards to items. Those links will quickly break.

**Comment by bit-pirate** [comment]
It might be good to extend that distribution-specific page to also contain more general information about licensing. E.g. May I build my own TurtleBot, may I sell my own TB, may I sell it with a different name and logo etc.
There are already related questions on ROS Answers.

**Comment by bit-pirate** [comment]
I'd like to see the companies countries on the distributors page, since it sometimes makes a big difference to the buyer and it's tiresome to check all distributors of one area for their location.

**Comment by pvandervorst** [comment]
Thanks for all your input! Looks like we've got a lot to work with.

I agree that TurtleBot.com should serve more as a portal that links people
to distributors, instructions, and the ROS wiki pages.

As far as the pages go, I think we should keep the build page. Analytics
shows that 26% of visitors click through to build, compared to 37% click
through to Buy, and I agree with Melonee's point of it being open source
both hardware and software.

Daniel, I agree that TurtleBot.com should not be a support page and should
be slimmed down. Perhaps the menu items should be changed to Buy, Build, &
Getting Started.

_Buy_
- List of distributors by region and country. I think a description for
  each distributor might make the page a bit unruly, but I like the idea.
- At the bottom of the page we should have a "want to become a
  distributor?" bar that allows people to get in contact with OSRF, and
  download a package that contains all of the distributor info needs.

_Build_
- Link to Bill's vender agnostic wiki with all parts and instruction for
  building your own.

_Getting started_
- Briefly describe hardware
- Briefly describe software
- Links (as Daniel mentioned under the links page + FAQs)

I think this is a much more slimmed down version, and serves the purpose of
a portal better. How does this sound?

**Comment by stonier** [comment]
+1 for the distributor bar - that makes good sense to have it exactly there on the distributors page rather than hidden in a faq.

Sounds good paul.

**Comment by sameerparekh** [comment]
Paul-- I like those ideas, and very much agree that the build page should still be there, but not list directly to distributors specific parts offerings-- links to subpages within distributors are a maintenance nightmare, so we should I think have a "rule" that we only link to a single page for each distributor, either that company's home page or their 'turtlebot landing page'.

Also listing distributors by country/region as well as continent makes a lot of sense. One thing I find interesting is that despite the fact that there are distributors for Asia and Europe, we still get a lot of Asia/Europe sales. I'm not sure if it's a function of the fact that North America is listed first on the page. 

Given that, I think that to be fair to all the regions and distributors, it would make sense to randomize somewhat the listing of distributors and regions. Ideally I think a map would make sense as far as regions go, and then once you click on your region then you end up with a list of distributors in that region, but the order is random, that way the distributor or region listed first doesn't just get more clicks just by virtue of being first. 

Doing this randomization / map would be a fair bit of work, but I think it would be a good idea.

**Comment by bit-pirate** [comment]
2013/6/13 Sameer Parekh notifications@github.com

> Paul-- I like those ideas, and very much agree that the build page should
> still be there, but not list directly to distributors specific parts
> offerings-- links to subpages within distributors are a maintenance
> nightmare, so we should I think have a "rule" that we only link to a single
> page for each distributor, either that company's home page or their
> 'turtlebot landing page'.
> 
> Also listing distributors by country/region as well as continent makes a
> lot of sense. One thing I find interesting is that despite the fact that
> there are distributors for Asia and Europe, we still get a lot of
> Asia/Europe sales. I'm not sure if it's a function of the fact that North
> America is listed first on the page.

I guess this situation is more due to the fact that we have only two
distributors set up in Europe/Asia and the new ones are still awaiting
responses to their distribution requests.

>  Given that, I think that to be fair to all the regions and distributors,
> it would make sense to randomize somewhat the listing of distributors and
> regions. Ideally I think a map would make sense as far as regions go, and
> then once you click on your region then you end up with a list of
> distributors in that region, but the order is random, that way the
> distributor or region listed first doesn't just get more clicks just by
> virtue of being first.
> 
> Doing this randomization / map would be a fair bit of work, but I think it
> would be a good idea.

A map would look nice! We are using one on our website:
http://kobuki.yujinrobot.com/store/ (scroll down a bit). I'm not sure
though, if the order is so important. I wouldn't mind a map centred on the
US - where TurtleBot was born - and save the time for creating the
randomised map. What do the others think?

**Comment by sameerparekh** [comment]
That map looks great, and the way you've done it removes any need to do
any kind of random ordering of distributors. Would you be willing to
contribute it to the turtlebot site? Do others think that would be a
good choice for the distributors page?

Marcus Liebhardt wrote:

**Comment by mmwise** [comment]
I agree with having the map. I would prefer to see the build it yourself docs on the turtlebot.com website. it's not updated that often and it's basically a zip file with some docs. This would keep the site in a sense distributor agnostic, which is what we try to do as much as possible.

**Comment by bit-pirate** [comment]
2013/6/14 Melonee Wise notifications@github.com

> I agree with having the map. I would prefer to see the build it yourself
> docs on the turtlebot.com website. it's not updated that often and it's
> basically a zip file with some docs. This would keep the site in a sense
> distributor agnostic, which is what we try to do as much as possible.

What about others, who'd like to show their TurtleBot mods and variants?
Having such projects side by side with the original build instructions,
could increase interest in TB.

>  --
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot.com/issues/4#issuecomment-19427340
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by mmwise** [comment]
some of this has already been started over at make projects, which has more visibility and is more associated with the maker community..Also Make has a nice interface for making instructions and adding photos.. It might be good to publicize this more, below are links to the current projects that people have posted. 

http://blog.makezine.com/projects/assemble-a-turtlebot/
http://blog.makezine.com/projects/add-a-demo-button-to-your-turtlebot/
http://blog.makezine.com/projects/create-cables-for-the-turtlebot-power-board/
http://blog.makezine.com/projects/build-a-turtlebot-robotic-arm-trossen-robotics-version/
http://blog.makezine.com/projects/wiring-and-attaching-an-arm-to-your-turtlebot/
http://blog.makezine.com/projects/build-your-own-turtlebot-plates/
http://blog.makezine.com/projects/build-an-arm-for-your-turtlebot/
http://blog.makezine.com/projects/build-your-own-turtlebot-2-standoff/

**Comment by tfoote** [comment]
+1 for using existing infrastructure.

**Comment by stonier** [comment]
I didn't realise the make projects site had more than the turtlebot arm. I think that's a nice off-site resource, although I wish their page wasn't so interruptive with adds and social buttons (I dont mind either, just not interrupting the flow) - it looks chinese!

1) Perhaps we can redirect the build it page there as well instead of a docs/zip file?
2) Advertise the link with the turtlebot search keyword: http://blog.makezine.com/search/?q=turtlebot

Everything else is starting to sound great, thanks Paul.

**Comment by tfoote** [comment]
The Make project site is very cluttered now.

There seems to be change under way at Make: Projects  we probably need to
talk to them about what is coming there.

```
Welcome to the new Make: Projects! User accounts are temporarily disabled.
If you contributed on our old platform, you can still view your projects
here, and we're working on an easy way to edit them in the future. If you'd
like access to update a project, email us atprojects@makezine.com.
```

**Comment by pvandervorst** [comment]
Perhaps we could set up a blog.turtlebot.com where we repost the make
projects in one location? The blog would have to be maintained by an OSRF
rep, however, to make sure it is vender agnostic.

**Comment by tfoote** [comment]
Closing this as outdated. We've done at least one redesign since then.
