### ISSUE TITLE
Redesign page footer

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot.com#5]
Currently it holds the original inventor and some distributors. Is there any idea behind this (what it should be used for)?

Since we already run out of space to list all distributors, I suggest we remove all logos there and only add the logo of OSRF  (+ link), since they are now officially in charge of the TurtleBot.

**Comment by rgariepy** [comment]
OK with that - are there any other relevant social media links besides G+?

-R

**Comment by pvandervorst** [comment]
I agree, it's getting a bit too much. OSRF and social media links are good
to have in the footer.

**Comment by mmwise** [comment]
I'd like to get a pointer for the turtlebot videos channel on youtube.. http://www.youtube.com/turtlebotvideo. so that people can get a better sense of what can be done with TurtleBot

**Comment by stonier** [comment]
+1 for video link

**Comment by bit-pirate** [comment]
:+1:

**Comment by sameerparekh** [comment]
+1

**Comment by bit-pirate** [comment]
What's the status on this? Is there any reason why this change hasn't been applied yet?

**Comment by pvandervorst** [comment]
Done.

On Wed, Aug 14, 2013 at 12:06 AM, Marcus Liebhardt <notifications@github.com

**Comment by bit-pirate** [comment]
Looking good. Thanks!
