### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by sameerparekh** [turtlebot/turtlebot.com#6]
Do we have site analytics a-la google analytics or other traffic analysis on the site? Would be helpful to know where people are going from various pages and which pages they are landing on first.

**Comment by sameerparekh** [comment]
Sorry didn't see the post in the design thread referring to analytics. Can I get a look at that?

**Comment by tfoote** [comment]
Yes, send me a google email and I can give you access.

**Comment by sameerparekh** [comment]
Thanks, please use sameer@falkorsystems.com

-s

Tully Foote wrote:
