### ISSUE TITLE
Change IHE link to www.iheartengineering.com

### ISSUE THREAD

**Issue by sameerparekh** [turtlebot/turtlebot.com#7]
It appears we've decided to remove the distributor-specific bits from the build page, so I will not post all the broken links on there, but we'd like to change the IHE link on 

http://www.turtlebot.com/distributors.html (and elsewhere)

to go to http://www.iheartengineering.com/ 

rather than http://store.iheartengineering.com/ 

(Right now it's just a redirect, but we're going to change that soon.)

Thanks

**Comment by pvandervorst** [comment]
Done

**Comment by sameerparekh** [comment]
Thanks!
