### ISSUE TITLE
legacy information in FAQ page

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot.com#9]
I see some legacy information is written in FAQ page.

Links : turtlebotinfo@willowgarage.com, Turtlebot Announce list, 
Questions : "I pre-ordered a TurtleBot kit from Willow Garage; what happens to my order?"

I think it would be better to remove for now until we get ready with correct information.

**Comment by pvandervorst** [comment]
Fixed

**Comment by stonier** [comment]
Need updates on the faq page for the email links:
- turtlebotinfo@willowgarage.com -> turtlebot@osrfoundation.org
- turtlebot announcement list -> https://groups.google.com/forum/#!forum/ros-sig-turtlebot

**Comment by pvandervorst** [comment]
Done.
